// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
static partial class Polyfill
{
	extension(UInt128)
	{
		/// <summary>
		/// Computes the base-10 logarithm of a value.
		/// </summary>
		public static UInt128 Log10(UInt128 value) =>
			(UInt128) Log10Core(value);
		/// <summary>
		/// Produces the full product of two unsigned 128-bit numbers.
		/// </summary>
		public static UInt128 BigMul(UInt128 left, UInt128 right, out UInt128 lower) =>
			BigMulCore(left, right, out lower);
	}
	static UInt128 BigMulCore(UInt128 left, UInt128 right, out UInt128 lower)
	{
		unchecked
		{
			UInt128 leftLower = (ulong) left;
			UInt128 leftUpper = (ulong) (left >> 64);
			UInt128 rightLower = (ulong) right;
			UInt128 rightUpper = (ulong) (right >> 64);
			var lowerLower = leftLower * rightLower;
			var middle = leftUpper * rightLower + (lowerLower >> 64);
			var middleLower = leftLower * rightUpper + (ulong) middle;
			lower = (middleLower << 64) | (ulong) lowerLower;
			return leftUpper * rightUpper + (middle >> 64) + (middleLower >> 64);
		}
	}
}
