// <auto-generated />
#pragma warning disable


namespace Polyfills;

using System;
using System.Collections;
using System.ComponentModel;

static partial class Polyfill
{
    /// <summary>
    /// Deconstructs the current <see cref="DictionaryEntry"/>.
    /// </summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.dictionaryentry.deconstruct?view=net-10.0#system-collections-dictionaryentry-deconstruct(system-object@-system-object@)
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct(this DictionaryEntry target, out object key, out object? value)
    {
        key = target.Key;
        value = target.Value;
    }
}
