// <auto-generated />
#pragma warning disable
#if PolyUseEmbeddedAttribute
#endif
#if PolyPublic
#endif
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.KeyValuePair))]