// <auto-generated />
#pragma warning disable
#pragma warning disable
namespace Polyfills;
using System;
static partial class Polyfill
{
	extension(Guid target)
	{
		/// <summary>
		/// Gets the variant field of the <see cref="Guid"/>.
		/// </summary>
		public int Variant =>
			HighNibble(target, 8);
		/// <summary>
		/// Gets the version field of the <see cref="Guid"/>.
		/// </summary>
		public int Version =>
			HighNibble(target, 7);
	}
	static int HighNibble(Guid value, int index)
	{
		return value.ToByteArray()[index] >> 4;
	}
}
