// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Runtime.CompilerServices;
using System;
#if PolyPublic
public
#endif
static partial class Guard
{
	/// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is greater than or equal <paramref name="other"/>.</summary>
	/// <param name="value">The argument to validate as less than <paramref name="other"/>.</param>
	/// <param name="other">The value to compare with <paramref name="value"/>.</param>
	/// <param name="name">The name of the parameter with which <paramref name="value"/> corresponds.</param>
	public static T NotGreaterThanOrEqual<T>(T value, T other, [CallerArgumentExpression(nameof(value))] string? name = null)
		where T : IComparable<T> =>
		Ensure.NotGreaterThanOrEqual(value, other, name);
}
