// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Runtime.CompilerServices;
#if PolyPublic
public
#endif
static partial class Guard
{
	/// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is equal to <paramref name="other"/>.</summary>
	/// <param name="value">The argument to validate as not equal to <paramref name="other"/>.</param>
	/// <param name="other">The value to compare with <paramref name="value"/>.</param>
	/// <param name="name">The name of the parameter with which <paramref name="value"/> corresponds.</param>
	public static T NotEqual<T>(T value, T other, [CallerArgumentExpression(nameof(value))] string? name = null) =>
		Ensure.NotEqual(value, other, name);
}
