// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Text;
using System;
using System.Security.Cryptography;
static partial class Polyfill
{
	static readonly Guid AllBitsSetValue = new(-1, -1, -1, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF);
	extension(Guid)
	{
		/// <summary>A read-only instance of the <see cref="Guid" /> structure whose value is all ones.</summary>
		public static Guid AllBitsSet => AllBitsSetValue;
#if FeatureMemory
		/// <summary>
		/// Tries to parse a span of UTF-8 bytes into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, out Guid result) =>
			Guid.TryParse(Encoding.UTF8.GetString(utf8Text), out result);
		/// <summary>
		/// Parse a span of UTF-8 bytes into a value.
		/// </summary>
		public static Guid Parse(ReadOnlySpan<byte> utf8Text) =>
			Guid.Parse(Encoding.UTF8.GetString(utf8Text));
#endif
	}
}
