// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Runtime.CompilerServices;
using System.Text;
static partial class Polyfill
{
#if AllowUnsafeBlocks
#else
#endif
}