// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Text;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
#if FeatureMemory
using System.Buffers;
#endif
static partial class Polyfill
{
}