// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Linq;
static partial class Polyfill
{
	/// <summary>
	/// Generic version of Type.IsAssignableTo https://learn.microsoft.com/en-us/dotnet/api/system.type.isassignableto.
	/// </summary>
	public static bool IsAssignableTo<T>(this Type target) =>
		typeof(T).IsAssignableFrom(target);
	/// <summary>
	/// Generic version of Type.IsAssignableFrom https://learn.microsoft.com/en-us/dotnet/api/system.type.isassignablefrom.
	/// </summary>
	public static bool IsAssignableFrom<T>(this Type target) =>
		target.IsAssignableFrom(typeof(T));
}
