// <auto-generated />
#pragma warning disable
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#if FeatureValueTuple

    //https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Take.cs
    /// <summary>Returns a specified range of contiguous elements from a sequence.</summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.take?view=net-10.0#system-linq-enumerable-take-1(system-collections-generic-ienumerable((-0))-system-range)
    public static IEnumerable<TSource> Take<TSource>(
        this IEnumerable<TSource> target,
        Range range)
    {
        if (IsEmptyArray(target))
        {
            return [];
        }

        var start = range.Start;
        var end = range.End;
        var isStartIndexFromEnd = start.IsFromEnd;
        var isEndIndexFromEnd = end.IsFromEnd;
        var startIndex = start.Value;
        var endIndex = end.Value;

        if (isStartIndexFromEnd)
        {
            if (startIndex == 0 || (isEndIndexFromEnd && endIndex >= startIndex))
            {
                return [];
            }
        }
        else if (!isEndIndexFromEnd)
        {
            return startIndex >= endIndex ? [] : TakeRangeIterator(target, startIndex, endIndex);
        }

        return TakeRangeFromEndIterator(target, isStartIndexFromEnd, startIndex, isEndIndexFromEnd, endIndex);
    }

#endif
