// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Collections.Generic;
using System.Linq;
static partial class Polyfill
{
	/// <summary>
	/// Produces a set items excluding <paramref name="item"/> by using the default equality comparer to compare values.
	/// </summary>
	public static IEnumerable<TSource> Except<TSource>(
		this IEnumerable<TSource> target,
		TSource item) =>
		Except<TSource>(target, item, null);
	/// <summary>
	/// Produces a set items excluding <paramref name="item"/> by using <paramref name="comparer"/> to compare values.
	/// </summary>
	public static IEnumerable<TSource> Except<TSource>(
		this IEnumerable<TSource> target,
		TSource item,
		IEqualityComparer<TSource>? comparer)
	{
		var set = new HashSet<TSource>(comparer) {item};
		foreach (var element in target)
		{
			if (set.Add(element))
			{
				yield return element;
			}
		}
	}
	/// <summary>
	/// Produces the set difference of two sequences by <paramref name="comparer"/> to compare values.
	/// </summary>
	public static IEnumerable<TSource> Except<TSource>(
		this IEnumerable<TSource> target,
		IEqualityComparer<TSource>? comparer,
		params TSource[] items) =>
		target.Except((IEnumerable<TSource>)items, comparer);
}
