// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Collections;
static partial class Polyfill
{
	/// <summary>
	/// Returns the number of bits set to <see langword="true"/> in the <see cref="BitArray"/>.
	/// </summary>
	public static int PopCount(this BitArray target)
	{
		var count = 0;
		for (var index = 0; index < target.Length; index++)
		{
			if (target[index])
			{
				count++;
			}
		}
		return count;
	}
}
