// <auto-generated />

#pragma warning disable

#if FeatureMemory
#if AllowUnsafeBlocks
#else
#endif
#if AllowUnsafeBlocks
#else
#endif
#endif
#if AllowUnsafeBlocks && FeatureMemory
#else
#endif
#if AllowUnsafeBlocks && FeatureMemory
#else
#endif
#if FeatureMemory
#if AllowUnsafeBlocks
#else
#endif
#endif