// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Globalization;
static partial class Polyfill
{
	extension(DateTime target)
	{
		/// <summary>
		/// Gets the nanosecond component of the time represented by the current <see cref="DateTime"/> object.
		/// </summary>
		public int Nanosecond =>
			(int) (target.TicksComponent() % TicksPerMicrosecond) * 100;
		/// <summary>
		/// Gets the microsecond component of the time represented by the current <see cref="DateTime"/> object.
		/// </summary>
		public int Microsecond =>
			(int) (target.TicksComponent() % TicksPerMicrosecond) * 1000;
		long TicksComponent()
		{
			var noSeconds = new DateTime(target.Year, target.Month, target.Day, target.Hour, target.Minute, 0, target.Kind);
			var secondsPart = target - noSeconds;
			return secondsPart.Ticks;
		}
	}
	extension(DateTime)
	{
		/// <summary>
		/// Tries to parse a string into a value.
		/// </summary>
		public static bool TryParse(string? s, IFormatProvider? provider, out DateTime result) =>
			DateTime.TryParse(s, provider, DateTimeStyles.None, out result);
#if FeatureMemory
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out DateTime result) =>
			DateTime.TryParse(s.ToString(), provider, DateTimeStyles.None, out result);
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<char> s, out DateTime result) =>
			DateTime.TryParse(s.ToString(), null, DateTimeStyles.None, out result);
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, DateTimeStyles styles, out DateTime result) =>
			DateTime.TryParse(s.ToString(), provider, styles, out result);
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParseExact(ReadOnlySpan<char> s, string format, IFormatProvider? provider, DateTimeStyles style, out DateTime result) =>
			DateTime.TryParseExact(s.ToString(), format, provider, style, out result);
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParseExact(ReadOnlySpan<char> s, ReadOnlySpan<char> format, IFormatProvider? provider, DateTimeStyles styles, out DateTime result) =>
			DateTime.TryParseExact(s.ToString(), format.ToString(), provider, styles, out result);
#endif
	}
}
