// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
static partial class Polyfill
{
	/// <summary>
	/// Removes a key and its value from the table, and returns the removed value.
	/// </summary>
	public static bool Remove<TKey, TValue>(
		this ConditionalWeakTable<TKey, TValue> target,
		TKey key,
		[MaybeNullWhen(false)] out TValue value)
		where TKey : class
		where TValue : class
	{
		if (target.TryGetValue(key, out value) &&
			target.Remove(key))
		{
			return true;
		}
		value = null;
		return false;
	}
}
