// <auto-generated />
#pragma warning disable
#nullable enable
namespace Polyfills;
using System;
using System.Globalization;
static partial class Polyfill
{
	extension(DateTimeOffset target)
	{
		/// <summary>
		/// Gets the nanosecond component of the time represented by the current <see cref="DateTimeOffset"/> object.
		/// </summary>
		public int Nanosecond =>
			(int) (target.TicksComponent() % TicksPerMicrosecond) * 100;
		/// <summary>
		/// Gets the microsecond component of the time represented by the current <see cref="DateTimeOffset"/> object.
		/// </summary>
		public int Microsecond =>
			(int) (target.TicksComponent() % TicksPerMicrosecond) * 1000;
		long TicksComponent()
		{
			var noSeconds = new DateTimeOffset(target.Year, target.Month, target.Day, target.Hour, target.Minute, 0, target.Offset);
			var secondsPart = target - noSeconds;
			return secondsPart.Ticks;
		}
	}
	extension(DateTimeOffset)
	{
		/// <summary>
		/// Tries to parse a string into a value.
		/// </summary>
		public static bool TryParse(string? s, IFormatProvider? provider, out DateTimeOffset result) =>
			DateTimeOffset.TryParse(s, provider, DateTimeStyles.None, out result);
#if FeatureMemory
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out DateTimeOffset result) =>
			DateTimeOffset.TryParse(s.ToString(), provider, DateTimeStyles.None, out result);
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<char> input, out DateTimeOffset result) =>
			DateTimeOffset.TryParse(input.ToString(), null, DateTimeStyles.None, out result);
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, DateTimeStyles styles, out DateTimeOffset result) =>
			DateTimeOffset.TryParse(s.ToString(), provider, styles, out result);
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParseExact(ReadOnlySpan<char> input, string format, IFormatProvider? provider, DateTimeStyles styles, out DateTimeOffset result) =>
			DateTimeOffset.TryParseExact(input.ToString(), format, provider, styles, out result);
#endif
	}
}
