// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
static partial class Polyfill
{
    /// <summary>Returns a read-only <see cref="ReadOnlyCollection{T}" /> wrapper for the current collection.</summary>
    public static ReadOnlyCollection<T> AsReadOnly<T>(this IList<T> target) =>
        new(target);
#if FeatureMemory
    /// <summary>Adds the elements of the specified span to the end of the <see cref="List{T}"/>.</summary>
    public static void AddRange<T>(this List<T> target, ReadOnlySpan<T> source)
    {
        foreach (var item in source)
        {
            target.Add(item);
        }
    }
    /// <summary>Inserts the elements of a span into the <see cref="List{T}"/> at the specified index.</summary>
    public static void InsertRange<T>(this List<T> target, int index, ReadOnlySpan<T> source)
    {
        for (var i = 0; i < source.Length; i++)
        {
            var item = source[i];
            target.Insert(i + index, item);
        }
    }
    /// <summary>Copies the entire <see cref="List{T}"/> to a span.</summary>
    public static void CopyTo<T>(this List<T> target, Span<T> destination)
    {
        for (var index = 0; index < target.Count; index++)
        {
            destination[index] = target[index];
        }
    }
#endif
    /// <summary>
    /// Ensures that the capacity of this list is at least the specified capacity. If the current capacity is less than capacity, it is increased to at least the specified capacity.
    /// </summary>
    public static void EnsureCapacity<T>(this List<T> target, int capacity)
    {
    }
    /// <summary>
    /// Sets the capacity to the actual number of elements in the <see cref="List{T}"/>, if that number is less than a threshold value.
    /// </summary>
    public static void TrimExcess<T>(this List<T> target)
    {
    }
}
