// <auto-generated />

#pragma warning disable

#if !NET5_0_OR_GREATER
namespace Polyfills;

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if PolyPublic
public
#endif
static partial class ObsoleteAttributePolyfill
{
    extension(ObsoleteAttribute target)
    {
        /// <summary>
        /// Gets or sets the URL for corresponding documentation. The API accepts a format string instead of an actual URL, creating a generic URL that includes the diagnostic ID.
        /// </summary>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.obsoleteattribute.urlformat?view=net-10.0
        public string? UrlFormat
        {
            get => null;
            set {  }
        }
    }
}
#endif