// <auto-generated />

using System.Runtime.CompilerServices;

#pragma warning disable

#if FeatureMemory

namespace Polyfills;

using System;
using System.Buffers;
using System.Collections.Generic;

static partial class Polyfill
{
#if NET8_0_OR_GREATER && !NET10_0_OR_GREATER

    /// <summary>
    /// Indicates whether a specified value occurs within a read-only span.
    /// </summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.contains#system-memoryextensions-contains-1(system-readonlyspan((-0))-0-system-collections-generic-iequalitycomparer((-0)))
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool Contains<T>(this ReadOnlySpan<T> span, T value, IEqualityComparer<T>? comparer = null) =>
        span.IndexOf(value, comparer) >= 0;

#endif
}

#endif