// <auto-generated />
#pragma warning disable

#if NETFRAMEWORK || NETSTANDARD2_0

namespace Polyfill;

using System.Threading.Tasks;

static partial class Polyfill
{
    extension(ValueTask)
    {
        /// <summary>Gets a task that has already completed successfully.</summary>
        public static ValueTask CompletedTask => default;
    }
}
#endif
