// <auto-generated />
#pragma warning disable

#if FeatureMemory
namespace Polyfills;

using System.Text;
using System;
using System.Diagnostics.CodeAnalysis;

static partial class Polyfill
{
#if !NET8_0_OR_GREATER

    /// <summary>
    /// Tries to format the value of the current instance into the provided span of characters.
    /// </summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.guid.tryformat?view=net-10.0#system-guid-tryformat(system-span((system-byte))-system-int32@-system-readonlyspan((system-char)))
    public static bool TryFormat(this Guid target, Span<byte> utf8Destination, out int bytesWritten, [StringSyntax(StringSyntaxAttribute.GuidFormat)] ReadOnlySpan<char> format = default) =>
        target.DoFormat(utf8Destination, out bytesWritten, format);

#endif
}
#endif