// <auto-generated />
#pragma warning disable

#if FeatureMemory

namespace Polyfills;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static partial class Polyfill
{

#if !AllowUnsafeBlocks && !NETSTANDARD2_1_OR_GREATER && !NETCOREAPP2_0_OR_GREATER

    [StructLayout(LayoutKind.Explicit)]
    struct BitConverter_Unknown<T1, T2>
    {
        [FieldOffset(0)]
        public T1 _field1;
        [FieldOffset(0)]
        public T2 _field2;
    }

#endif

    extension(BitConverter)
    {

#if !NETSTANDARD2_1_OR_GREATER && !NETCOREAPP2_0_OR_GREATER

        /// <summary>
        /// Reinterprets the specified 32-bit integer as a single-precision floating-point value.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.int32bitstosingle
#if AllowUnsafeBlocks
        public static unsafe float Int32BitsToSingle(int value)
        {
            return Unsafe.AsRef<float>(Unsafe.AsPointer(ref value));
        }
#else
        public static float Int32BitsToSingle(int value)
        {
            var i = new BitConverter_Unknown<int, float>();
            i._field1 = value;
            return i._field2;
        }
#endif

#endif

#if !NET6_0_OR_GREATER

        /// <summary>
        /// Converts the specified 32-bit unsigned integer to a single-precision floating point number.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.uint32bitstosingle
        public static float UInt32BitsToSingle(uint value)
        {
            return BitConverter.Int32BitsToSingle((int)value);
        }

#endif

#if !NET6_0_OR_GREATER

        /// <summary>
        /// Converts the specified 64-bit unsigned integer to a double-precision floating point number.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.uint64bitstodouble
        public static double UInt64BitsToDouble(ulong value)
        {
            return BitConverter.Int64BitsToDouble((long)value);
        }

#endif

#if !NETSTANDARD2_1_OR_GREATER && !NETCOREAPP2_0_OR_GREATER

        /// <summary>
        /// Converts a single-precision floating-point value into an integer.
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.singletoint32bits
#if AllowUnsafeBlocks
        public static unsafe int SingleToInt32Bits(float value)
        {
            return Unsafe.AsRef<int>(Unsafe.AsPointer(ref value));
        }
#else
        public static int SingleToInt32Bits(float value)
        {
            var i = new BitConverter_Unknown<float, int>();
            i._field1 = value;
            return i._field2;
        }
#endif

#endif

#if !NET6_0_OR_GREATER

        /// <summary>
        /// Converts the specified single-precision floating point number to a 32-bit unsigned integer.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.singletouint32bits
        public static uint SingleToUInt32Bits(float value)
        {
            return (uint)BitConverter.SingleToInt32Bits(value);
        }

#endif

#if !NET6_0_OR_GREATER

        /// <summary>
        /// Converts the specified double-precision floating point number to a 64-bit unsigned integer.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.doubletouint64bits
        public static ulong DoubleToUInt64Bits(double value)
        {
            return (ulong)BitConverter.DoubleToInt64Bits(value);
        }

#endif

    }

}

#endif
