// <auto-generated />

#pragma warning disable

#if FeatureMemory

namespace Polyfills;

using System;
using System.Runtime.InteropServices;
using System.Text;

static partial class Polyfill
{
#if !NET8_0_OR_GREATER

    /// <summary>Decodes into a span of chars a set of bytes from the specified read-only span if the destination is large enough.</summary>
    /// <param name="bytes">A read-only span containing the sequence of bytes to decode.</param>
    /// <param name="chars">The character span receiving the decoded bytes.</param>
    /// <param name="charsWritten">Upon successful completion of the operation, the number of chars decoded into <paramref name="chars"/>.</param>
    /// <returns><see langword="true"/> if all of the characters were decoded into the destination; <see langword="false"/> if the destination was too small to contain all the decoded chars.</returns>
    ///Link: https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding.trygetchars?view=net-10.0
    public static bool TryGetChars(this Encoding target, ReadOnlySpan<byte> bytes, Span<char> chars, out int charsWritten)
    {
        int required = target.GetCharCount(bytes);
        if (required <= chars.Length)
        {
            charsWritten = target.GetChars(bytes, chars);
            return true;
        }

        charsWritten = 0;
        return false;
    }

    /// <summary>Encodes into a span of bytes a set of characters from the specified read-only span if the destination is large enough.</summary>
    /// <param name="chars">The span containing the set of characters to encode.</param>
    /// <param name="bytes">The byte span to hold the encoded bytes.</param>
    /// <param name="bytesWritten">Upon successful completion of the operation, the number of bytes encoded into <paramref name="bytes"/>.</param>
    /// <returns><see langword="true"/> if all of the characters were encoded into the destination; <see langword="false"/> if the destination was too small to contain all the encoded bytes.</returns>
    ///Link: https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding.trygetbytes?view=net-10.0
    public static bool TryGetBytes(this Encoding target, ReadOnlySpan<char> chars, Span<byte> bytes, out int bytesWritten)
    {
        int required = target.GetByteCount(chars);
        if (required <= bytes.Length)
        {
            bytesWritten = target.GetBytes(chars, bytes);
            return true;
        }

        bytesWritten = 0;
        return false;
    }
#endif
}

#endif