// <auto-generated />
#pragma warning disable

namespace Polyfills;

using System;

static partial class Polyfill
{
    extension(TimeSpan)
    {
#if !NET10_0_OR_GREATER
        /// <summary>
        /// Returns a <see cref="TimeSpan"/> that represents a specified number of milliseconds.
        /// </summary>
        /// <param name="value">A number of milliseconds.</param>
        /// <returns>An object that represents <paramref name="value"/>.</returns>
        /// <exception cref="OverflowException">
        /// <paramref name="value"/> is less than <see cref="MinValue"/> or greater than <see cref="MaxValue"/>.
        /// -or-
        /// <paramref name="value"/> is <see cref="double.PositiveInfinity"/>.
        /// -or-
        /// <paramref name="value"/> is <see cref="double.NegativeInfinity"/>.
        /// </exception>
        /// <exception cref="ArgumentException">
        /// <paramref name="value"/> is equal to <see cref="double.NaN"/>.
        /// </exception>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.timespan.frommilliseconds?view=net-10.0
        public static TimeSpan FromMilliseconds(long milliseconds)
        {
            const long TicksPerMillisecond = 10000;
            const long MaxMilliseconds = long.MaxValue / TicksPerMillisecond;
            const long MinMilliseconds = long.MinValue / TicksPerMillisecond;

            if (milliseconds < MinMilliseconds || milliseconds > MaxMilliseconds)
            {
                throw new OverflowException("TimeSpan overflowed because the duration is too long.");
            }

            return new TimeSpan(milliseconds * TicksPerMillisecond);
        }
#endif
    }
}
