// <auto-generated />

using System.IO.Compression;

#pragma warning disable

#if FeatureCompression && ((NETFRAMEWORK && !NET472_OR_GREATER) || NETSTANDARD2_0)
namespace Polyfills;

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if PolyPublic
public
#endif
static partial class ZipArchiveEntryPolyfill
{
    extension(ZipArchiveEntry target)
    {
        /// <summary>
        /// OS and application specific file attributes.
        /// </summary>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchiveentry.externalattributes?view=net-10.0
        public int ExternalAttributes
        {
            get => 0;
            set {  }
        }
    }
}
#endif