// <auto-generated />
#pragma warning disable

#if !NET10_0_OR_GREATER && FeatureCompression

namespace Polyfills;

using System;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

static partial class Polyfill
{
    extension(ZipFile)
    {
        /// <summary>
        /// Asynchronously extracts all the files in the specified archive to a directory on the file system.
        /// </summary>
        /// <param name="sourceArchiveFileName">The path to the archive to extract.</param>
        /// <param name="destinationDirectoryName">The path to the directory in which to place the extracted files.</param>
        /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the asynchronous extract operation.</returns>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectoryasync?view=net-10.0
        public static Task ExtractToDirectoryAsync(
            string sourceArchiveFileName,
            string destinationDirectoryName,
            CancellationToken cancellationToken = default) =>
            ExtractToDirectoryAsync(sourceArchiveFileName, destinationDirectoryName, false, cancellationToken);

        /// <summary>
        /// Asynchronously extracts all the files in the specified archive to a directory on the file system.
        /// </summary>
        /// <param name="sourceArchiveFileName">The path to the archive to extract.</param>
        /// <param name="destinationDirectoryName">The path to the directory in which to place the extracted files.</param>
        /// <param name="overwriteFiles">true to overwrite existing files; false otherwise.</param>
        /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the asynchronous extract operation.</returns>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectoryasync?view=net-10.0
        public static Task ExtractToDirectoryAsync(
            string sourceArchiveFileName,
            string destinationDirectoryName,
            bool overwriteFiles,
            CancellationToken cancellationToken = default) =>
            Task.Run(() => ExtractToDirectoryPolyfill(sourceArchiveFileName, destinationDirectoryName, overwriteFiles), cancellationToken);

        /// <summary>
        /// Asynchronously extracts all the files in the specified archive to a directory on the file system and uses the specified character encoding for entry names.
        /// </summary>
        /// <param name="sourceArchiveFileName">The path to the archive to extract.</param>
        /// <param name="destinationDirectoryName">The path to the directory in which to place the extracted files.</param>
        /// <param name="entryNameEncoding">The encoding to use when reading entry names in this archive.</param>
        /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the asynchronous extract operation.</returns>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectoryasync?view=net-10.0
        public static Task ExtractToDirectoryAsync(
            string sourceArchiveFileName,
            string destinationDirectoryName,
            Encoding entryNameEncoding,
            CancellationToken cancellationToken = default) =>
            ExtractToDirectoryAsync(sourceArchiveFileName, destinationDirectoryName, entryNameEncoding, false, cancellationToken);

        /// <summary>
        /// Asynchronously extracts all the files in the specified archive to a directory on the file system and uses the specified character encoding for entry names.
        /// </summary>
        /// <param name="sourceArchiveFileName">The path to the archive to extract.</param>
        /// <param name="destinationDirectoryName">The path to the directory in which to place the extracted files.</param>
        /// <param name="entryNameEncoding">The encoding to use when reading entry names in this archive.</param>
        /// <param name="overwriteFiles">true to overwrite existing files; false otherwise.</param>
        /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the asynchronous extract operation.</returns>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectoryasync?view=net-10.0
        public static Task ExtractToDirectoryAsync(
            string sourceArchiveFileName,
            string destinationDirectoryName,
            Encoding entryNameEncoding,
            bool overwriteFiles,
            CancellationToken cancellationToken = default) =>
            Task.Run(() => ExtractToDirectoryPolyfill(sourceArchiveFileName, destinationDirectoryName, entryNameEncoding, overwriteFiles), cancellationToken);

        // Helper method to handle overwriteFiles polyfill for pre-.NET 8.0
        static void ExtractToDirectoryPolyfill(
            string sourceArchiveFileName,
            string destinationDirectoryName,
            bool overwriteFiles)
        {
#if NET8_0_OR_GREATER
            ZipFile.ExtractToDirectory(sourceArchiveFileName, destinationDirectoryName, overwriteFiles);
#else
            if (overwriteFiles && Directory.Exists(destinationDirectoryName))
            {
                Directory.Delete(destinationDirectoryName, true);
            }
            ZipFile.ExtractToDirectory(sourceArchiveFileName, destinationDirectoryName);
#endif
        }

        // Helper method to handle overwriteFiles polyfill for pre-.NET 8.0 with encoding
        static void ExtractToDirectoryPolyfill(
            string sourceArchiveFileName,
            string destinationDirectoryName,
            Encoding entryNameEncoding,
            bool overwriteFiles)
        {
#if NET8_0_OR_GREATER
            ZipFile.ExtractToDirectory(sourceArchiveFileName, destinationDirectoryName, entryNameEncoding, overwriteFiles);
#else
            if (overwriteFiles && Directory.Exists(destinationDirectoryName))
            {
                Directory.Delete(destinationDirectoryName, true);
            }
            ZipFile.ExtractToDirectory(sourceArchiveFileName, destinationDirectoryName, entryNameEncoding);
#endif
        }

        /// <summary>
        /// Asynchronously creates a zip archive that contains the files and directories from the specified directory.
        /// </summary>
        /// <param name="sourceDirectoryName">The path to the directory to archive.</param>
        /// <param name="destinationArchiveFileName">The path of the archive to create.</param>
        /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the asynchronous create operation.</returns>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.createfromdirectoryasync?view=net-10.0
        public static Task CreateFromDirectoryAsync(
            string sourceDirectoryName,
            string destinationArchiveFileName,
            CancellationToken cancellationToken = default) =>
            CreateFromDirectoryAsync(sourceDirectoryName, destinationArchiveFileName, CompressionLevel.Optimal, false, cancellationToken);

        /// <summary>
        /// Asynchronously creates a zip archive that contains the files and directories from the specified directory and uses the specified compression level.
        /// </summary>
        /// <param name="sourceDirectoryName">The path to the directory to archive.</param>
        /// <param name="destinationArchiveFileName">The path of the archive to create.</param>
        /// <param name="compressionLevel">The compression level to use.</param>
        /// <param name="includeBaseDirectory">true to include the directory name from sourceDirectoryName at the root of the archive; false otherwise.</param>
        /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the asynchronous create operation.</returns>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.createfromdirectoryasync?view=net-10.0
        public static Task CreateFromDirectoryAsync(
            string sourceDirectoryName,
            string destinationArchiveFileName,
            CompressionLevel compressionLevel,
            bool includeBaseDirectory,
            CancellationToken cancellationToken = default) =>
            Task.Run(() => ZipFile.CreateFromDirectory(sourceDirectoryName, destinationArchiveFileName, compressionLevel, includeBaseDirectory), cancellationToken);

        /// <summary>
        /// Asynchronously creates a zip archive that contains the files and directories from the specified directory, uses the specified compression level and character encoding for entry names.
        /// </summary>
        /// <param name="sourceDirectoryName">The path to the directory to archive.</param>
        /// <param name="destinationArchiveFileName">The path of the archive to create.</param>
        /// <param name="compressionLevel">The compression level to use.</param>
        /// <param name="includeBaseDirectory">true to include the directory name from sourceDirectoryName at the root of the archive; false otherwise.</param>
        /// <param name="entryNameEncoding">The encoding to use when reading or writing entry names in this archive.</param>
        /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the asynchronous create operation.</returns>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.createfromdirectoryasync?view=net-10.0
        public static Task CreateFromDirectoryAsync(
            string sourceDirectoryName,
            string destinationArchiveFileName,
            CompressionLevel compressionLevel,
            bool includeBaseDirectory,
            Encoding entryNameEncoding,
            CancellationToken cancellationToken = default) =>
            Task.Run(() => ZipFile.CreateFromDirectory(sourceDirectoryName, destinationArchiveFileName, compressionLevel, includeBaseDirectory, entryNameEncoding), cancellationToken);
    }
}

#endif
