// <auto-generated />
#pragma warning disable
#if FeatureMemory
namespace Polyfills;
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
static partial class Polyfill
{
	extension(BitConverter)
	{
		/// <summary>
		/// Converts the specified 32-bit unsigned integer to a single-precision floating point number.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static float UInt32BitsToSingle(uint value)
		{
			return BitConverter.Int32BitsToSingle((int)value);
		}
		/// <summary>
		/// Converts the specified 64-bit unsigned integer to a double-precision floating point number.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static double UInt64BitsToDouble(ulong value)
		{
			return BitConverter.Int64BitsToDouble((long)value);
		}
		/// <summary>
		/// Converts the specified single-precision floating point number to a 32-bit unsigned integer.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static uint SingleToUInt32Bits(float value)
		{
			return (uint)BitConverter.SingleToInt32Bits(value);
		}
		/// <summary>
		/// Converts the specified double-precision floating point number to a 64-bit unsigned integer.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static ulong DoubleToUInt64Bits(double value)
		{
			return (ulong)BitConverter.DoubleToInt64Bits(value);
		}
		/// <summary>
		/// Returns the specified half-precision floating point value as an array of bytes.
		/// </summary>
		public static byte[] GetBytes(Half value)
		{
			var bytes = new byte[2];
			MemoryMarshal.Write(bytes, ref value);
			return bytes;
		}
		/// <summary>
		/// Converts a half-precision floating point value into a 16-bit signed integer.
		/// </summary>
		public static short HalfToInt16Bits(Half value)
		{
			Span<byte> buffer = stackalloc byte[2];
			MemoryMarshal.Write(buffer, ref value);
			return MemoryMarshal.Read<short>(buffer);
		}
		/// <summary>
		/// Converts a half-precision floating point value into a 16-bit unsigned integer.
		/// </summary>
		public static ushort HalfToUInt16Bits(Half value)
		{
			Span<byte> buffer = stackalloc byte[2];
			MemoryMarshal.Write(buffer, ref value);
			return MemoryMarshal.Read<ushort>(buffer);
		}
		/// <summary>
		/// Reinterprets the specified 16-bit signed integer as a half-precision floating point value.
		/// </summary>
		public static Half Int16BitsToHalf(short value)
		{
			Span<byte> buffer = stackalloc byte[2];
			MemoryMarshal.Write(buffer, ref value);
			return MemoryMarshal.Read<Half>(buffer);
		}
		/// <summary>
		/// Reinterprets the specified 16-bit unsigned integer as a half-precision floating point value.
		/// </summary>
		public static Half UInt16BitsToHalf(ushort value)
		{
			Span<byte> buffer = stackalloc byte[2];
			MemoryMarshal.Write(buffer, ref value);
			return MemoryMarshal.Read<Half>(buffer);
		}
		/// <summary>
		/// Returns a half-precision floating point number converted from two bytes at a specified position in a byte array.
		/// </summary>
		public static Half ToHalf(byte[] value, int startIndex)
		{
			GuardTwoBytes(value, startIndex);
			return MemoryMarshal.Read<Half>(value.AsSpan(startIndex));
		}
		/// <summary>
		/// Converts a read-only byte span into a half-precision floating point value.
		/// </summary>
		public static Half ToHalf(ReadOnlySpan<byte> value)
		{
			if (value.Length < 2)
			{
				throw new ArgumentOutOfRangeException(nameof(value));
			}
			return MemoryMarshal.Read<Half>(value);
		}
		/// <summary>
		/// Converts a half-precision floating point value into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, Half value)
		{
			if (destination.Length < 2)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
	}
	static void GuardTwoBytes(byte[] value, int startIndex)
	{
		if (value == null)
		{
			throw new ArgumentNullException(nameof(value));
		}
		if (startIndex < 0 ||
			startIndex >= value.Length)
		{
			throw new ArgumentOutOfRangeException(nameof(startIndex), "Index was out of range. Must be non-negative and less than the size of the collection.");
		}
		if (startIndex > value.Length - 2)
		{
			throw new ArgumentException("The array starting from the specified index is not long enough to read a value of the specified type.", nameof(value));
		}
	}
}
#endif
