// <auto-generated />
#pragma warning disable
#if FeatureValueTask
namespace Polyfills;
using System;
#if FeatureMemory
using System.Buffers;
using System.Runtime.InteropServices;
#endif
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;
static partial class Polyfill
{
#if FeatureMemory
	/// <summary>
	/// Receives data and returns the endpoint of the sending host.
	/// </summary>
	/// <remarks>
	/// On frameworks earlier than net6.0 the cancellation token is observed by closing the underlying socket,
	/// which leaves the <see cref="Socket"/> instance unusable for subsequent operations. On net6.0+ the BCL
	/// implementation cancels only the in-flight operation.
	/// </remarks>
	public static ValueTask<SocketReceiveFromResult> ReceiveFromAsync(
		this Socket target,
		Memory<byte> buffer,
		SocketFlags socketFlags,
		EndPoint remoteEndPoint,
		CancellationToken cancellationToken = default)
	{
		if (remoteEndPoint is null)
		{
			throw new ArgumentNullException(nameof(remoteEndPoint));
		}
		if (cancellationToken.IsCancellationRequested)
		{
			return new ValueTask<SocketReceiveFromResult>(Task.FromCanceled<SocketReceiveFromResult>(cancellationToken));
		}
		return new ValueTask<SocketReceiveFromResult>(ReceiveFromWithCancellationAsync(target, buffer, socketFlags, remoteEndPoint, cancellationToken));
	}
	static Task<SocketReceiveFromResult> ReceiveFromWithCancellationAsync(
		Socket target,
		Memory<byte> buffer,
		SocketFlags socketFlags,
		EndPoint remoteEndPoint,
		CancellationToken cancellationToken)
	{
		var taskCompletionSource = new TaskCompletionSource<SocketReceiveFromResult>(TaskCreationOptions.RunContinuationsAsynchronously);
		var args = new SocketAsyncEventArgs
		{
			RemoteEndPoint = remoteEndPoint,
			SocketFlags = socketFlags
		};
		CancellationTokenRegistration registration = default;
		var segment = GetArraySegment(buffer, out var rentedBuffer);
		args.SetBuffer(segment.Array, segment.Offset, segment.Count);
		void Cleanup(SocketAsyncEventArgs eventArgs)
		{
			registration.Dispose();
			eventArgs.Completed -= OnCompleted;
			eventArgs.Dispose();
			if (rentedBuffer is not null)
			{
				ArrayPool<byte>.Shared.Return(rentedBuffer);
				rentedBuffer = null;
			}
		}
		void Complete(SocketAsyncEventArgs eventArgs)
		{
			if (eventArgs.SocketError == SocketError.Success)
			{
				if (rentedBuffer is not null)
				{
					rentedBuffer.AsMemory(0, eventArgs.BytesTransferred).CopyTo(buffer);
				}
				var result = new SocketReceiveFromResult
				{
					ReceivedBytes = eventArgs.BytesTransferred,
					RemoteEndPoint = eventArgs.RemoteEndPoint!
				};
				Cleanup(eventArgs);
				taskCompletionSource.TrySetResult(result);
				return;
			}
			Cleanup(eventArgs);
			if (cancellationToken.IsCancellationRequested)
			{
				taskCompletionSource.TrySetCanceled(cancellationToken);
				return;
			}
			taskCompletionSource.TrySetException(new SocketException((int) eventArgs.SocketError));
		}
		void OnCompleted(object? _, SocketAsyncEventArgs eventArgs) =>
			Complete(eventArgs);
		args.Completed += OnCompleted;
		if (cancellationToken.CanBeCanceled)
		{
			registration = cancellationToken.Register(() => target.Close());
		}
		try
		{
			if (!target.ReceiveFromAsync(args))
			{
				Complete(args);
			}
		}
		catch (ObjectDisposedException) when (cancellationToken.IsCancellationRequested)
		{
			Cleanup(args);
			return Task.FromCanceled<SocketReceiveFromResult>(cancellationToken);
		}
		catch (SocketException) when (cancellationToken.IsCancellationRequested)
		{
			Cleanup(args);
			return Task.FromCanceled<SocketReceiveFromResult>(cancellationToken);
		}
		catch
		{
			Cleanup(args);
			throw;
		}
		return taskCompletionSource.Task;
	}
	/// <summary>
	/// Sends data to the specified remote host.
	/// </summary>
	/// <remarks>
	/// On frameworks earlier than net6.0 the cancellation token is observed by closing the underlying socket,
	/// which leaves the <see cref="Socket"/> instance unusable for subsequent operations. On net6.0+ the BCL
	/// implementation cancels only the in-flight operation.
	/// </remarks>
	public static ValueTask<int> SendToAsync(
		this Socket target,
		ReadOnlyMemory<byte> buffer,
		SocketFlags socketFlags,
		EndPoint remoteEP,
		CancellationToken cancellationToken = default)
	{
		if (remoteEP is null)
		{
			throw new ArgumentNullException(nameof(remoteEP));
		}
		if (cancellationToken.IsCancellationRequested)
		{
			return new ValueTask<int>(Task.FromCanceled<int>(cancellationToken));
		}
		return new ValueTask<int>(SendToWithCancellationAsync(target, buffer, socketFlags, remoteEP, cancellationToken));
	}
	static Task<int> SendToWithCancellationAsync(
		Socket target,
		ReadOnlyMemory<byte> buffer,
		SocketFlags socketFlags,
		EndPoint remoteEP,
		CancellationToken cancellationToken)
	{
		var taskCompletionSource = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
		var args = new SocketAsyncEventArgs
		{
			RemoteEndPoint = remoteEP,
			SocketFlags = socketFlags
		};
		CancellationTokenRegistration registration = default;
		var segment = GetArraySegment(buffer, out var rentedBuffer);
		args.SetBuffer(segment.Array, segment.Offset, segment.Count);
		void Cleanup(SocketAsyncEventArgs eventArgs)
		{
			registration.Dispose();
			eventArgs.Completed -= OnCompleted;
			eventArgs.Dispose();
			if (rentedBuffer is not null)
			{
				ArrayPool<byte>.Shared.Return(rentedBuffer);
				rentedBuffer = null;
			}
		}
		void Complete(SocketAsyncEventArgs eventArgs)
		{
			Cleanup(eventArgs);
			if (eventArgs.SocketError == SocketError.Success)
			{
				taskCompletionSource.TrySetResult(eventArgs.BytesTransferred);
				return;
			}
			if (cancellationToken.IsCancellationRequested)
			{
				taskCompletionSource.TrySetCanceled(cancellationToken);
				return;
			}
			taskCompletionSource.TrySetException(new SocketException((int) eventArgs.SocketError));
		}
		void OnCompleted(object? _, SocketAsyncEventArgs eventArgs) =>
			Complete(eventArgs);
		args.Completed += OnCompleted;
		if (cancellationToken.CanBeCanceled)
		{
			registration = cancellationToken.Register(() => target.Close());
		}
		try
		{
			if (!target.SendToAsync(args))
			{
				Complete(args);
			}
		}
		catch (ObjectDisposedException) when (cancellationToken.IsCancellationRequested)
		{
			Cleanup(args);
			return Task.FromCanceled<int>(cancellationToken);
		}
		catch (SocketException) when (cancellationToken.IsCancellationRequested)
		{
			Cleanup(args);
			return Task.FromCanceled<int>(cancellationToken);
		}
		catch
		{
			Cleanup(args);
			throw;
		}
		return taskCompletionSource.Task;
	}
	static ArraySegment<byte> GetArraySegment(
		Memory<byte> buffer,
		out byte[]? rentedBuffer)
	{
		if (MemoryMarshal.TryGetArray((ReadOnlyMemory<byte>) buffer, out ArraySegment<byte> segment))
		{
			rentedBuffer = null;
			return segment;
		}
		rentedBuffer = ArrayPool<byte>.Shared.Rent(buffer.Length);
		return new ArraySegment<byte>(rentedBuffer, 0, buffer.Length);
	}
	static ArraySegment<byte> GetArraySegment(
		ReadOnlyMemory<byte> buffer,
		out byte[]? rentedBuffer)
	{
		if (MemoryMarshal.TryGetArray(buffer, out ArraySegment<byte> segment))
		{
			rentedBuffer = null;
			return segment;
		}
		rentedBuffer = ArrayPool<byte>.Shared.Rent(buffer.Length);
		buffer.Span.CopyTo(rentedBuffer.AsSpan());
		return new ArraySegment<byte>(rentedBuffer, 0, buffer.Length);
	}
#endif
	/// <summary>
	/// Disconnects a connected socket from the remote host.
	/// </summary>
	/// <remarks>
	/// On frameworks earlier than net6.0 the cancellation token is observed by closing the underlying socket,
	/// which defeats the <c>reuseSocket</c> flag on cancellation. On net6.0+ the BCL implementation cancels
	/// only the in-flight operation.
	/// </remarks>
	public static ValueTask DisconnectAsync(
		this Socket target,
		bool reuseSocket,
		CancellationToken cancellationToken = default)
	{
		if (cancellationToken.IsCancellationRequested)
		{
			return new ValueTask(Task.FromCanceled(cancellationToken));
		}
		return new ValueTask(DisconnectWithCancellationAsync(target, reuseSocket, cancellationToken));
	}
	static Task DisconnectWithCancellationAsync(
		Socket target,
		bool reuseSocket,
		CancellationToken cancellationToken)
	{
		var taskCompletionSource = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
		var args = new SocketAsyncEventArgs
		{
			DisconnectReuseSocket = reuseSocket
		};
		CancellationTokenRegistration registration = default;
		void Complete(SocketAsyncEventArgs eventArgs)
		{
			registration.Dispose();
			eventArgs.Completed -= OnCompleted;
			eventArgs.Dispose();
			if (eventArgs.SocketError == SocketError.Success)
			{
				taskCompletionSource.TrySetResult(true);
				return;
			}
			if (cancellationToken.IsCancellationRequested)
			{
				taskCompletionSource.TrySetCanceled(cancellationToken);
				return;
			}
			taskCompletionSource.TrySetException(new SocketException((int) eventArgs.SocketError));
		}
		void OnCompleted(object? _, SocketAsyncEventArgs eventArgs) =>
			Complete(eventArgs);
		args.Completed += OnCompleted;
		if (cancellationToken.CanBeCanceled)
		{
			registration = cancellationToken.Register(() => target.Close());
		}
		try
		{
			if (!target.DisconnectAsync(args))
			{
				Complete(args);
			}
		}
		catch (ObjectDisposedException) when (cancellationToken.IsCancellationRequested)
		{
			registration.Dispose();
			args.Completed -= OnCompleted;
			args.Dispose();
			return Task.FromCanceled(cancellationToken);
		}
		catch (SocketException) when (cancellationToken.IsCancellationRequested)
		{
			registration.Dispose();
			args.Completed -= OnCompleted;
			args.Dispose();
			return Task.FromCanceled(cancellationToken);
		}
		catch
		{
			registration.Dispose();
			args.Completed -= OnCompleted;
			args.Dispose();
			throw;
		}
		return taskCompletionSource.Task;
	}
}
#endif
