// <auto-generated />
#pragma warning disable
#nullable enable
#if FeatureMemory
#pragma warning disable
namespace System.Buffers;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
/// <summary>
/// Represents a heap-based, array-backed output sink into which <typeparamref name="T"/> data can be written.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
sealed class ArrayBufferWriter<T> :
	IBufferWriter<T>
{
	const int ArrayMaxLength = 0x7FFFFFC7;
	const int DefaultInitialBufferSize = 256;
	T[] buffer;
	int index;
	/// <summary>
	/// Initializes a new instance of the <see cref="ArrayBufferWriter{T}"/> class with the default initial capacity.
	/// </summary>
	public ArrayBufferWriter()
	{
		buffer = Array.Empty<T>();
		index = 0;
	}
	/// <summary>
	/// Initializes a new instance of the <see cref="ArrayBufferWriter{T}"/> class with the specified initial capacity.
	/// </summary>
	/// <param name="initialCapacity">The minimum capacity with which to initialize the underlying buffer.</param>
	/// <exception cref="ArgumentException"><paramref name="initialCapacity"/> is less than or equal to 0.</exception>
	public ArrayBufferWriter(int initialCapacity)
	{
		if (initialCapacity <= 0)
		{
			throw new ArgumentException(null, nameof(initialCapacity));
		}
		buffer = new T[initialCapacity];
		index = 0;
	}
	/// <summary>
	/// Gets the data written to the underlying buffer so far, as a <see cref="ReadOnlyMemory{T}"/>.
	/// </summary>
	public ReadOnlyMemory<T> WrittenMemory => buffer.AsMemory(0, index);
	/// <summary>
	/// Gets the data written to the underlying buffer so far, as a <see cref="ReadOnlySpan{T}"/>.
	/// </summary>
	public ReadOnlySpan<T> WrittenSpan => buffer.AsSpan(0, index);
	/// <summary>
	/// Gets the amount of data written to the underlying buffer so far.
	/// </summary>
	public int WrittenCount => index;
	/// <summary>
	/// Gets the total amount of space within the underlying buffer.
	/// </summary>
	public int Capacity => buffer.Length;
	/// <summary>
	/// Gets the amount of space available that can still be written into without forcing the underlying buffer to grow.
	/// </summary>
	public int FreeCapacity => buffer.Length - index;
	/// <summary>
	/// Clears the data written to the underlying buffer.
	/// </summary>
	public void Clear()
	{
		buffer.AsSpan(0, index).Clear();
		index = 0;
	}
	/// <summary>
	/// Resets the data written to the underlying buffer without zeroing its contents.
	/// </summary>
	public void ResetWrittenCount() =>
		index = 0;
	/// <summary>
	/// Notifies the <see cref="IBufferWriter{T}"/> that <paramref name="count"/> data items were written to the output <see cref="Span{T}"/> or <see cref="Memory{T}"/>.
	/// </summary>
	/// <param name="count">The number of data items written.</param>
	/// <exception cref="ArgumentException"><paramref name="count"/> is negative.</exception>
	/// <exception cref="InvalidOperationException">The method call attempts to advance past the end of the underlying buffer.</exception>
	public void Advance(int count)
	{
		if (count < 0)
		{
			throw new ArgumentException(null, nameof(count));
		}
		if (index > buffer.Length - count)
		{
			throw new InvalidOperationException($"Cannot advance past the end of the buffer, which has a size of {buffer.Length}.");
		}
		index += count;
	}
	/// <summary>
	/// Returns a <see cref="Memory{T}"/> to write to that is at least the requested size, as specified by <paramref name="sizeHint"/>.
	/// </summary>
	/// <param name="sizeHint">The minimum length of the returned <see cref="Memory{T}"/>. If 0, a non-empty buffer is returned.</param>
	/// <exception cref="ArgumentException"><paramref name="sizeHint"/> is negative.</exception>
	public Memory<T> GetMemory(int sizeHint = 0)
	{
		CheckAndResizeBuffer(sizeHint);
		return buffer.AsMemory(index);
	}
	/// <summary>
	/// Returns a <see cref="Span{T}"/> to write to that is at least the requested size, as specified by <paramref name="sizeHint"/>.
	/// </summary>
	/// <param name="sizeHint">The minimum length of the returned <see cref="Span{T}"/>. If 0, a non-empty buffer is returned.</param>
	/// <exception cref="ArgumentException"><paramref name="sizeHint"/> is negative.</exception>
	public Span<T> GetSpan(int sizeHint = 0)
	{
		CheckAndResizeBuffer(sizeHint);
		return buffer.AsSpan(index);
	}
	void CheckAndResizeBuffer(int sizeHint)
	{
		if (sizeHint < 0)
		{
			throw new ArgumentException(null, nameof(sizeHint));
		}
		if (sizeHint == 0)
		{
			sizeHint = 1;
		}
		if (sizeHint <= FreeCapacity)
		{
			return;
		}
		var currentLength = buffer.Length;
		var growBy = Math.Max(sizeHint, currentLength);
		if (currentLength == 0)
		{
			growBy = Math.Max(growBy, DefaultInitialBufferSize);
		}
		var newSize = currentLength + growBy;
		if ((uint) newSize > ArrayMaxLength)
		{
			var needed = (uint) (currentLength - FreeCapacity + sizeHint);
			if (needed > ArrayMaxLength)
			{
				throw new OutOfMemoryException($"Cannot allocate a buffer of size {needed}.");
			}
			newSize = ArrayMaxLength;
		}
		Array.Resize(ref buffer, newSize);
	}
}
#endif
