// <auto-generated />
#pragma warning disable
#if FeatureMemory
#nullable enable
namespace System.Buffers;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
delegate void ReadOnlySpanAction<T, in TArg>(ReadOnlySpan<T> span, TArg arg);
#endif
