// <auto-generated />
#pragma warning disable


namespace Polyfills;

using System;
using System.Globalization;
using System.Text;

static partial class Polyfill
{
    extension(long)
    {

#if FeatureMemory


        /// <summary>
        /// Tries to parse a span of UTF-8 characters into a value.
        /// </summary>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.int64.tryparse?view=net-10.0#system-int64-tryparse(system-readonlyspan((system-byte))-system-iformatprovider-system-int64@)
        public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out long result) =>
            long.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Integer, provider, out result);

        /// <summary>
        /// Tries to parse a span of UTF-8 characters into a value.
        /// </summary>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.int64.tryparse?view=net-10.0#system-int64-tryparse(system-readonlyspan((system-byte))-system-globalization-numberstyles-system-iformatprovider-system-int64@)
        public static bool TryParse(ReadOnlySpan<byte> utf8Text, NumberStyles style, IFormatProvider? provider, out long result) =>
            long.TryParse(Encoding.UTF8.GetString(utf8Text), style, provider, out result);

        /// <summary>
        /// Tries to convert a UTF-8 character span containing the string representation of a number to its 64-bit signed integer equivalent.
        /// </summary>
        //Link: https://learn.microsoft.com/en-us/dotnet/api/system.int64.tryparse?view=net-10.0#system-int64-tryparse(system-readonlyspan((system-char))-system-globalization-numberstyles-system-iformatprovider-system-int64@)
        public static bool TryParse(ReadOnlySpan<byte> utf8Text, out long result) =>
            long.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Integer, null, out result);




#endif
    }
}