// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Globalization;
using System.Text;
static partial class Polyfill
{
	extension(nint)
	{
#if FeatureMemory
		/// <summary>
		/// Tries to parse a span of UTF-8 characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out nint result) =>
			nint.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Integer, provider, out result);
		/// <summary>
		/// Tries to parse a span of UTF-8 characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, NumberStyles style, IFormatProvider? provider, out nint result) =>
			nint.TryParse(Encoding.UTF8.GetString(utf8Text), style, provider, out result);
		/// <summary>
		/// Tries to parse a span of UTF-8 characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, out nint result) =>
			nint.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Integer, null, out result);
#endif
		/// <summary>
		/// Computes the base-10 logarithm of a value.
		/// </summary>
		public static nint Log10(nint value)
		{
			if (value < 0)
			{
				throw new ArgumentOutOfRangeException(nameof(value), value, "value must be a non-negative number.");
			}
			return (nint) Log10Core((ulong) value);
		}
		/// <summary>
		/// Produces the full product of two native-sized signed numbers.
		/// </summary>
		public static nint BigMul(nint left, nint right, out nint lower)
		{
			unchecked
			{
				if (IntPtr.Size == 4)
				{
					var product = (long) left * right;
					lower = (nint) (int) product;
					return (nint) (int) (product >> 32);
				}
				var upper = Math.BigMul((long) left, (long) right, out var low);
				lower = (nint) low;
				return (nint) upper;
			}
		}
	}
}
