// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Globalization;
using System.Text;
static partial class Polyfill
{
	extension(float)
	{
#if FeatureMemory
		/// <summary>
		/// Tries to parse a span of UTF-8 characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out float result) =>
			float.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Float, provider, out result);
		/// <summary>
		/// Tries to parse a span of UTF-8 characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, NumberStyles style, IFormatProvider? provider, out float result) =>
			float.TryParse(Encoding.UTF8.GetString(utf8Text), style, provider, out result);
		/// <summary>
		/// Tries to convert a UTF-8 character span containing the string representation of a number to its single-precision floating-point number equivalent.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, out float result) =>
			float.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Float, null, out result);
#endif
	}
}
