// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Globalization;
using System.Text;
static partial class Polyfill
{
	extension(ulong)
	{
#if FeatureMemory
		/// <summary>
		/// Tries to parse a span of UTF-8 characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out ulong result) =>
			ulong.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Integer, provider, out result);
		/// <summary>
		/// Tries to parse a span of UTF-8 characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte>utf8Text, NumberStyles style, IFormatProvider? provider, out ulong result) =>
			ulong.TryParse(Encoding.UTF8.GetString(utf8Text), style, provider, out result);
		/// <summary>
		/// Tries to convert a UTF-8 character span containing the string representation of a number to its ulong equivalent.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<byte> utf8Text, out ulong result) =>
			ulong.TryParse(Encoding.UTF8.GetString(utf8Text), NumberStyles.Integer, null, out result);
#endif
		/// <summary>
		/// Produces the full product of two unsigned 64-bit numbers.
		/// </summary>
		public static UInt128 BigMul(ulong left, ulong right) =>
			(UInt128) left * right;
		/// <summary>
		/// Computes the base-10 logarithm of a value.
		/// </summary>
		public static ulong Log10(ulong value) =>
			(ulong) Log10Core(value);
	}
}
