<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <AssemblyName>ConsumeOldStyle</AssemblyName>
    <RootNamespace>ConsumeOldStyle</RootNamespace>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS0162</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
    <Compile Include="StreamUsage.cs" />
    <Compile Include="..\Polyfill\Polyfill_Stream_Read.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\Polyfill\Polyfill.targets" />
</Project>
