// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Collections;
using System.ComponentModel;
static partial class Polyfill
{
    /// <summary>
    /// Deconstructs the current <see cref="DictionaryEntry"/>.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct(this DictionaryEntry target, out object key, out object? value)
    {
        key = target.Key;
        value = target.Value;
    }
}
