// <auto-generated />
#pragma warning disable
#if FeatureMemory
namespace Polyfills;
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
static partial class Polyfill
{
#if !AllowUnsafeBlocks
	[StructLayout(LayoutKind.Explicit)]
	struct BitConverter_Int32_Float
	{
		[FieldOffset(0)]
		public int _int;
		[FieldOffset(0)]
		public float _float;
	}
#endif
	extension(BitConverter)
	{
		/// <summary>
		/// Reinterprets the specified 32-bit integer as a single-precision floating-point value.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
#if AllowUnsafeBlocks
		public static unsafe float Int32BitsToSingle(int value)
		{
			return Unsafe.AsRef<float>(Unsafe.AsPointer(ref value));
		}
#else
		public static float Int32BitsToSingle(int value)
		{
			var i = new BitConverter_Int32_Float();
			i._int = value;
			return i._float;
		}
#endif
		/// <summary>
		/// Converts the specified 32-bit unsigned integer to a single-precision floating point number.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static float UInt32BitsToSingle(uint value)
		{
			return BitConverter.Int32BitsToSingle((int)value);
		}
		/// <summary>
		/// Converts the specified 64-bit unsigned integer to a double-precision floating point number.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static double UInt64BitsToDouble(ulong value)
		{
			return BitConverter.Int64BitsToDouble((long)value);
		}
		/// <summary>
		/// Converts a single-precision floating-point value into an integer.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
#if AllowUnsafeBlocks
		public static unsafe int SingleToInt32Bits(float value)
		{
			return Unsafe.AsRef<int>(Unsafe.AsPointer(ref value));
		}
#else
		public static int SingleToInt32Bits(float value)
		{
			var i = new BitConverter_Int32_Float();
			i._float = value;
			return i._int;
		}
#endif
		/// <summary>
		/// Converts the specified single-precision floating point number to a 32-bit unsigned integer.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static uint SingleToUInt32Bits(float value)
		{
			return (uint)BitConverter.SingleToInt32Bits(value);
		}
		/// <summary>
		/// Converts the specified double-precision floating point number to a 64-bit unsigned integer.
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static ulong DoubleToUInt64Bits(double value)
		{
			return (ulong)BitConverter.DoubleToInt64Bits(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a Boolean.
		/// </summary>
		public static bool ToBoolean(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 1);
			return value[0] != 0;
		}
		/// <summary>
		/// Converts a read-only byte span into a Char.
		/// </summary>
		public static char ToChar(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 2);
			return MemoryMarshal.Read<char>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a 16-bit signed integer.
		/// </summary>
		public static short ToInt16(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 2);
			return MemoryMarshal.Read<short>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a 32-bit signed integer.
		/// </summary>
		public static int ToInt32(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 4);
			return MemoryMarshal.Read<int>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a 64-bit signed integer.
		/// </summary>
		public static long ToInt64(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 8);
			return MemoryMarshal.Read<long>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a single-precision floating point number.
		/// </summary>
		public static float ToSingle(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 4);
			return MemoryMarshal.Read<float>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a double-precision floating point number.
		/// </summary>
		public static double ToDouble(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 8);
			return MemoryMarshal.Read<double>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a 16-bit unsigned integer.
		/// </summary>
		public static ushort ToUInt16(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 2);
			return MemoryMarshal.Read<ushort>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a 32-bit unsigned integer.
		/// </summary>
		public static uint ToUInt32(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 4);
			return MemoryMarshal.Read<uint>(value);
		}
		/// <summary>
		/// Converts a read-only byte span into a 64-bit unsigned integer.
		/// </summary>
		public static ulong ToUInt64(ReadOnlySpan<byte> value)
		{
			GuardSpan(value, 8);
			return MemoryMarshal.Read<ulong>(value);
		}
		/// <summary>
		/// Converts a Boolean into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, bool value)
		{
			if (destination.Length < 1)
			{
				return false;
			}
			destination[0] = value ? (byte) 1 : (byte) 0;
			return true;
		}
		/// <summary>
		/// Converts a Char into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, char value)
		{
			if (destination.Length < 2)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a 16-bit signed integer into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, short value)
		{
			if (destination.Length < 2)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a 32-bit signed integer into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, int value)
		{
			if (destination.Length < 4)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a 64-bit signed integer into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, long value)
		{
			if (destination.Length < 8)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a single-precision floating point number into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, float value)
		{
			if (destination.Length < 4)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a double-precision floating point number into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, double value)
		{
			if (destination.Length < 8)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a 16-bit unsigned integer into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, ushort value)
		{
			if (destination.Length < 2)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a 32-bit unsigned integer into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, uint value)
		{
			if (destination.Length < 4)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
		/// <summary>
		/// Converts a 64-bit unsigned integer into a span of bytes.
		/// </summary>
		public static bool TryWriteBytes(Span<byte> destination, ulong value)
		{
			if (destination.Length < 8)
			{
				return false;
			}
			MemoryMarshal.Write(destination, ref value);
			return true;
		}
	}
	static void GuardSpan(ReadOnlySpan<byte> value, int size)
	{
		if (value.Length < size)
		{
			throw new ArgumentOutOfRangeException(nameof(value));
		}
	}
}
#endif
