// <auto-generated />
#pragma warning disable

#if FeatureMemory
#nullable enable
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
    #region AppendFormatted
    #region AppendFormatted T
    #endregion
    #region AppendFormatted ReadOnlySpan<char>
    #endregion
    #region AppendFormatted string
    #endregion
    #region AppendFormatted object
    #endregion
    #endregion
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.DefaultInterpolatedStringHandler))]
#endif