// <auto-generated />
#pragma warning disable
#if FeatureMemory
#if PolyUseEmbeddedAttribute
#endif
#if PolyPublic
#endif
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.Runtime.CompilerServices.DefaultInterpolatedStringHandler))]
#endif