// <auto-generated />
#pragma warning disable

#if !NET

namespace System.Diagnostics.CodeAnalysis;

using Targets = AttributeTargets;

/// <summary>
///   Specifies that the method or property will ensure that the listed field and property members have
///   not-<see langword="null"/> values.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[AttributeUsage(
    validOn: Targets.Method |
             Targets.Property,
    Inherited = false,
    AllowMultiple = true)]
#if PolyPublic
public
#endif
sealed class MemberNotNullAttribute :
    Attribute
{
    /// <summary>
    ///   Gets field or property member names.
    /// </summary>
    public string[] Members { get; }

    /// <summary>
    ///   Initializes the attribute with a field or property member.
    /// </summary>
    public MemberNotNullAttribute(string member) =>
        Members = [member];

    /// <summary>
    ///   Initializes the attribute with the list of field and property members.
    /// </summary>
    public MemberNotNullAttribute(params string[] members) =>
        Members = members;
}
#else
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.Diagnostics.CodeAnalysis.MemberNotNullAttribute))]
#endif