// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Runtime.CompilerServices;
using System.Text;
static partial class Polyfill
{
	/// <summary>Appends the specified interpolated string followed by the default line terminator to the end of the current StringBuilder object.</summary>
	public static StringBuilder AppendLine(
		StringBuilder target,
		[InterpolatedStringHandlerArgument(nameof(target))]
		ref StringBuilder.AppendInterpolatedStringHandler handler) =>
		target.AppendLine(ref handler);
	/// <summary>Appends the specified interpolated string followed by the default line terminator to the end of the current StringBuilder object.</summary>
	public static StringBuilder AppendLine(
		StringBuilder target,
		IFormatProvider? provider,
		[InterpolatedStringHandlerArgument(nameof(target), nameof(provider))]
		ref StringBuilder.AppendInterpolatedStringHandler handler) =>
		target.AppendLine(provider, ref handler);
}
