// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System;
#if PolyPublic
public
#endif
static partial class Ensure
{
	[return: NotNullIfNotNull(nameof(value))]
	public static string? NotWhiteSpace(
		string? value,
		[CallerArgumentExpression("value")] string name = "")
	{
		if (value == null)
		{
			return value;
		}
		ArgumentException.ThrowIfNullOrWhiteSpace(value, name);
		return value;
	}
#if FeatureMemory
	public static ReadOnlySpan<char> NotWhiteSpace(
		ReadOnlySpan<char> value,
		[CallerArgumentExpression("value")] string name = "")
	{
		if (value.Length == 0)
		{
			throw new ArgumentException("Argument cannot be empty.", name);
		}
		foreach (var ch in value)
		{
			if (!char.IsWhiteSpace(ch))
			{
				return value;
			}
		}
		throw new ArgumentException("Argument cannot be whitespace.", name);
	}
	[return: NotNullIfNotNull(nameof(value))]
	public static Memory<char>? NotWhiteSpace(
		Memory<char>? value,
		[CallerArgumentExpression("value")] string name = "")
	{
		if (value == null)
		{
			return value;
		}
		if (value.Value.Length == 0)
		{
			throw new ArgumentException("Argument cannot be empty.", name);
		}
		foreach (var ch in value.Value.Span)
		{
			if (!char.IsWhiteSpace(ch))
			{
				return value;
			}
		}
		throw new ArgumentException("Argument cannot be whitespace.", name);
	}
	[return: NotNullIfNotNull(nameof(value))]
	public static ReadOnlyMemory<char>? NotWhiteSpace(
		ReadOnlyMemory<char>? value,
		[CallerArgumentExpression("value")] string name = "")
	{
		if (value == null)
		{
			return value;
		}
		if (value.Value.Length == 0)
		{
			throw new ArgumentException("Argument cannot be empty.", name);
		}
		foreach (var ch in value.Value.Span)
		{
			if (!char.IsWhiteSpace(ch))
			{
				return value;
			}
		}
		throw new ArgumentException("Argument cannot be whitespace.", name);
	}
	public static Span<char> NotWhiteSpace(
		Span<char> value,
		[CallerArgumentExpression("value")] string name = "")
	{
		if (value.Length == 0)
		{
			throw new ArgumentException("Argument cannot be empty.", name);
		}
		foreach (var ch in value)
		{
			if (!char.IsWhiteSpace(ch))
			{
				return value;
			}
		}
		throw new ArgumentException("Argument cannot be whitespace.", name);
	}
#endif
}
