// <auto-generated />
#pragma warning disable
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.IO.EnumerationOptions))]
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.KeyValuePair))]
[assembly: TypeForwardedTo(typeof(System.IO.MatchCasing))]
[assembly: TypeForwardedTo(typeof(System.IO.MatchType))]
[assembly: TypeForwardedTo(typeof(System.Buffers.ReadOnlySpanAction<,>))]
[assembly: TypeForwardedTo(typeof(System.Buffers.SpanAction<,>))]
