// <auto-generated />
#pragma warning disable
#if FeatureMemory
namespace System.Text.RegularExpressions;
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
/// <summary>
/// Represents an enumerator containing the set of successful matches found by iteratively applying a regular expression pattern to the input span.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
ref struct ValueMatchEnumerator
{
	ReadOnlySpan<char> _input;
	ValueMatch _current;
	MatchCollection matchCollection;
	int index = 0;
	internal ValueMatchEnumerator(Regex regex, ReadOnlySpan<char> input, int startAt)
	{
		matchCollection = regex.Matches(input.ToString(), startAt);
		_input = input;
		_current = default;
	}
	public readonly ValueMatchEnumerator GetEnumerator() => this;
	public bool MoveNext()
	{
		if (index == matchCollection.Count)
		{
			return false;
		}
		var match = matchCollection[index];
		_current = new ValueMatch(match.Index, match.Length);
		index++;
		return true;
	}
	public readonly ValueMatch Current => _current;
}
#endif
