// <auto-generated />
#pragma warning disable

#if !NET

namespace System.Runtime.Versioning;

using Diagnostics;
using Diagnostics.CodeAnalysis;

/// <summary>
/// Records the platform that the project targeted.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[AttributeUsage(AttributeTargets.Assembly)]
#if PolyPublic
public
#endif
sealed class TargetPlatformAttribute(string platformName) :
    OSPlatformAttribute(platformName);
#else
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.Runtime.Versioning.TargetPlatformAttribute))]
#endif