// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Collections.Generic;
static partial class Polyfill
{
	/// <summary>
	/// Adds a value to the beginning of the sequence.
	/// </summary>
	public static IEnumerable<TSource> Prepend<TSource>(
		this IEnumerable<TSource> target,
		TSource element)
	{
		yield return element;
		foreach (var item in target)
		{
			yield return item;
		}
	}
}
