// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Collections.Generic;
static partial class Polyfill
{
    /// <summary>
    /// Creates a <see cref="HashSet{T}"/> from an <see cref="IEnumerable{T}"/> using the comparer to compare keys.
    /// </summary>
    public static HashSet<TSource> ToHashSet<TSource>(
        this IEnumerable<TSource> target,
        IEqualityComparer<TSource>? comparer = null) =>
        new(target, comparer);
}
