// <auto-generated />
#pragma warning disable
#nullable enable
#if FeatureMemory
#pragma warning disable
namespace System.IO;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System.Threading.Tasks;
/// <summary>
/// Provides a seekable, read-write <see cref="Stream"/> over a <see cref="Memory{Byte}"/> with fixed capacity.
/// </summary>
/// <remarks>
/// The underlying memory is not copied; reads and writes are served directly from it.
/// The stream cannot expand beyond the capacity of the memory it was created over.
/// </remarks>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
sealed class WritableMemoryStream :
	Stream
{
	Memory<byte> memory;
	long length;
	long position;
	bool disposed;
	/// <summary>
	/// Initializes a new instance of the <see cref="WritableMemoryStream"/> class over the specified <see cref="Memory{Byte}"/>.
	/// </summary>
	public WritableMemoryStream(Memory<byte> buffer)
	{
		memory = buffer;
		length = buffer.Length;
	}
	/// <inheritdoc/>
	public override bool CanRead => !disposed;
	/// <inheritdoc/>
	public override bool CanSeek => !disposed;
	/// <inheritdoc/>
	public override bool CanWrite => !disposed;
	/// <inheritdoc/>
	public override long Length
	{
		get
		{
			ThrowIfDisposed();
			return length;
		}
	}
	/// <inheritdoc/>
	public override long Position
	{
		get
		{
			ThrowIfDisposed();
			return position;
		}
		set
		{
			ThrowIfDisposed();
			if (value < 0)
			{
				throw new ArgumentOutOfRangeException(nameof(value));
			}
			position = value;
		}
	}
	/// <inheritdoc/>
	public override int Read(byte[] buffer, int offset, int count)
	{
		GuardRange(buffer, offset, count);
		ThrowIfDisposed();
		var toRead = Remaining(count);
		if (toRead == 0)
		{
			return 0;
		}
		memory.Span.Slice((int)position, toRead).CopyTo(buffer.AsSpan(offset, toRead));
		position += toRead;
		return toRead;
	}
	/// <inheritdoc/>
	public override int ReadByte()
	{
		ThrowIfDisposed();
		if (position >= length)
		{
			return -1;
		}
		var result = memory.Span[(int)position];
		position++;
		return result;
	}
	/// <inheritdoc/>
	public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
	{
		GuardRange(buffer, offset, count);
		ThrowIfDisposed();
		if (cancellationToken.IsCancellationRequested)
		{
			return Task.FromCanceled<int>(cancellationToken);
		}
		return Task.FromResult(Read(buffer, offset, count));
	}
	/// <inheritdoc/>
	public override void Write(byte[] buffer, int offset, int count)
	{
		GuardRange(buffer, offset, count);
		ThrowIfDisposed();
		GuardCapacity(count);
		if (count == 0)
		{
			return;
		}
		buffer.AsSpan(offset, count).CopyTo(memory.Span.Slice((int)position, count));
		Advance(count);
	}
	/// <inheritdoc/>
	public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
	{
		GuardRange(buffer, offset, count);
		ThrowIfDisposed();
		if (cancellationToken.IsCancellationRequested)
		{
			return Task.FromCanceled(cancellationToken);
		}
		Write(buffer, offset, count);
		return Task.CompletedTask;
	}
	/// <inheritdoc/>
	public override void SetLength(long value)
	{
		ThrowIfDisposed();
		if (value < 0)
		{
			throw new ArgumentOutOfRangeException(nameof(value));
		}
		if (value > memory.Length)
		{
			throw new NotSupportedException("Unable to expand length of this stream beyond its capacity.");
		}
		Grow(value);
		length = value;
		if (position > length)
		{
			position = length;
		}
	}
	void Grow(long newLength)
	{
		if (newLength > length)
		{
			memory.Span.Slice((int)length, (int)(newLength - length)).Clear();
		}
	}
	void Advance(int count)
	{
		Grow(position);
		position += count;
		if (position > length)
		{
			length = position;
		}
	}
	int Remaining(int count)
	{
		if (position >= length)
		{
			return 0;
		}
		return (int)Math.Min(length - position, count);
	}
	void GuardCapacity(int count)
	{
		if (count == 0)
		{
			return;
		}
		if (position > memory.Length - count)
		{
			throw new NotSupportedException("Unable to expand length of this stream beyond its capacity.");
		}
	}
	/// <inheritdoc/>
	public override long Seek(long offset, SeekOrigin origin)
	{
		ThrowIfDisposed();
		var basePosition = origin switch
		{
			SeekOrigin.Begin => 0L,
			SeekOrigin.Current => position,
			SeekOrigin.End => length,
			_ => throw new ArgumentException("Invalid seek origin.", nameof(origin))
		};
		if (offset > long.MaxValue - basePosition)
		{
			throw new ArgumentOutOfRangeException(nameof(offset));
		}
		var newPosition = basePosition + offset;
		if (newPosition < 0)
		{
			throw new IOException("An attempt was made to move the position before the beginning of the stream.");
		}
		position = newPosition;
		return position;
	}
	/// <inheritdoc/>
	public override void Flush()
	{
	}
	/// <inheritdoc/>
	public override Task FlushAsync(CancellationToken cancellationToken) =>
		cancellationToken.IsCancellationRequested ? Task.FromCanceled(cancellationToken) : Task.CompletedTask;
	/// <inheritdoc/>
	protected override void Dispose(bool disposing)
	{
		disposed = true;
		memory = default;
		base.Dispose(disposing);
	}
	void ThrowIfDisposed()
	{
		if (disposed)
		{
			throw new ObjectDisposedException(GetType().FullName);
		}
	}
	static void GuardRange(byte[] buffer, int offset, int count)
	{
		if (buffer == null)
		{
			throw new ArgumentNullException(nameof(buffer));
		}
		if (offset < 0)
		{
			throw new ArgumentOutOfRangeException(nameof(offset));
		}
		if (count < 0)
		{
			throw new ArgumentOutOfRangeException(nameof(count));
		}
		if (buffer.Length - offset < count)
		{
			throw new ArgumentException("The sum of offset and count is larger than the buffer length.");
		}
	}
}
#endif
