// <auto-generated />
#pragma warning disable
#if FeatureCompression
namespace Polyfills;
using System.IO.Compression;
using System;
static partial class Polyfill
{
    extension(ZipArchiveEntry target)
    {
        /// <summary>
        /// OS and application specific file attributes.
        /// </summary>
        public int ExternalAttributes
        {
            get => 0;
            set {  }
        }
    }
}
#endif
