// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
static partial class Polyfill
{
	extension(UInt128)
	{
		/// <summary>
		/// Computes the base-10 logarithm of a value.
		/// </summary>
		public static UInt128 Log10(UInt128 value) =>
			(UInt128) Log10Core(value);
	}
}
