// <auto-generated />

#pragma warning disable


namespace Polyfills;

using System.Threading.Tasks;

#if PolyPublic
public
#endif
static partial class Polyfill
{
    extension(ValueTask)
    {
        /// <summary>Gets a task that has already completed successfully.</summary>
        
        public static ValueTask CompletedTask => default;
    }
}
