// <auto-generated />
#pragma warning disable

#nullable enable
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
#if MONO
                case byte[] ba when index < ba.Length:
                    state = TranslateByte(ba[index]);
                    return true;
#endif
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(System.Reflection.NullabilityInfoContext))]
