// <auto-generated />

#pragma warning disable

namespace Polyfills;

using System.Numerics;
using System.Runtime.CompilerServices;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

#if PolyPublic
public
#endif

static partial class Guard
{
    /// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is not equal to <paramref name="other"/>.</summary>
    /// <param name="value">The argument to validate as equal to <paramref name="other"/>.</param>
    /// <param name="other">The value to compare with <paramref name="value"/>.</param>
    /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
    public static T Equal<T>(T value, T other, [CallerArgumentExpression(nameof(value))] string? paramName = null)
    {
        if (!EqualityComparer<T>.Default.Equals(value, other))
        {
            throw new ArgumentOutOfRangeException(paramName, value, string.Format("{0} ('{1}') must be equal to '{2}'.", paramName, (object?) value ?? "null", (object?) other ?? "null"));
        }

        return value;
    }
}