// <auto-generated />

using System.Diagnostics.CodeAnalysis;

#pragma warning disable

namespace Polyfills;

using System.Runtime.CompilerServices;
using System;

#if PolyPublic
public
#endif

static partial class Guard
{
    [return: NotNullIfNotNull(nameof(value))]
    public static string? NotWhiteSpace(
        string? value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
        if (value == null)
        {
            return value;
        }

#if NET8_0_OR_GREATER
        ArgumentException.ThrowIfNullOrWhiteSpace(value, argumentName);
        return value;
#else

        if (value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
#endif
    }
#if FeatureMemory

    public static ReadOnlySpan<char> NotWhiteSpace(
        ReadOnlySpan<char> value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
        if (value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
    }

    [return: NotNullIfNotNull(nameof(value))]
    public static Memory<char>? NotWhiteSpace(
        Memory<char>? value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
        if (value == null)
        {
            return value;
        }

        if (value.Value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value.Value.Span)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
    }

    [return: NotNullIfNotNull(nameof(value))]
    public static ReadOnlyMemory<char>? NotWhiteSpace(
        ReadOnlyMemory<char>? value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
        if (value == null)
        {
            return value;
        }

        if (value.Value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value.Value.Span)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
    }

    public static Span<char> NotWhiteSpace(
        Span<char> value,
        [CallerArgumentExpression("value")] string argumentName = "")
    {
        if (value.Length == 0)
        {
            throw new ArgumentException("Argument cannot be empty.", argumentName);
        }

        foreach (var ch in value)
        {
            if (!char.IsWhiteSpace(ch))
            {
                return value;
            }
        }

        throw new ArgumentException("Argument cannot be whitespace.", argumentName);
    }
#endif
}