<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>
  <Import Project="..\TestIncludes.targets" />
  <Import Project="..\Polyfill\Polyfill.targets" />
</Project>
