// <auto-generated />
#pragma warning disable
#if FeatureCompression
namespace Polyfills;
using System;
using System.Threading;
using System.Threading.Tasks;
using System.IO;
using System.IO.Compression;
static partial class Polyfill
{
	/// <summary>
	/// Opens the entry from the zip archive with the specified access mode.
	/// </summary>
	public static Stream Open(this ZipArchiveEntry target, FileAccess access) =>
		target.Open();
#if FeatureValueTask
	/// <summary>
	/// Asynchronously opens the entry from the zip archive with the specified access mode.
	/// </summary>
	public static ValueTask<Stream> OpenAsync(this ZipArchiveEntry target, FileAccess access, CancellationToken cancellationToken = default)
	{
		cancellationToken.ThrowIfCancellationRequested();
		return new ValueTask<Stream>(target.Open());
	}
#endif
}
#endif
