// <auto-generated />
#pragma warning disable

#if FeatureMemory

namespace Polyfills;

using System.ComponentModel;
using System.Runtime.CompilerServices;
using System;
using System.Text;

static partial class Polyfill
{


}

#endif
