global using TUnit.Core;
global using TUnit.Assertions;
global using TUnit.Assertions.Extensions;
global using System;
global using System.Diagnostics.CodeAnalysis;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Method = Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax;
global using Property = Microsoft.CodeAnalysis.CSharp.Syntax.PropertyDeclarationSyntax;
global using Member = Microsoft.CodeAnalysis.CSharp.Syntax.MemberDeclarationSyntax;
global using Type = Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax;
global using Class = Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax;
global using Parameter = Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax;
