// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Collections.Concurrent;
static partial class Polyfill
{
	/// <summary>
	/// Removes all values from the <see cref="ConcurrentQueue{T}"/>.
	/// </summary>
	public static void Clear<T>(this ConcurrentQueue<T> target)
	{
		while (target.TryDequeue(out _));
	}
}
