// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
static partial class Polyfill
{
	extension(Type target)
	{
		/// <summary>
		/// Gets a value that indicates whether the current Type represents a type parameter in the definition of a generic method.
		/// </summary>
		public bool IsGenericMethodParameter =>
			target.IsGenericParameter &&
			target.DeclaringMethod != null;
	}
	extension(Type target)
	{
		/// <summary>
		/// Returns the underlying type argument of the current nullable value type, or <c>null</c> if the current type is not a nullable value type.
		/// </summary>
		public Type? GetNullableUnderlyingType() =>
			Nullable.GetUnderlyingType(target);
	}
}
