// <auto-generated />
#pragma warning disable
#nullable enable
namespace Polyfills;
using System;
using System.Globalization;
static partial class Polyfill
{
	extension(DateTimeOffset)
	{
#if FeatureMemory
		/// <summary>
		/// Tries to parse a span of characters into a value.
		/// </summary>
		public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out DateTimeOffset result) =>
			DateTimeOffset.TryParse(s.ToString(), provider, DateTimeStyles.None, out result);
#endif
	}
}
