// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Globalization;
static partial class Polyfill
{
	extension(ISOWeek)
	{
		/// <summary>
		/// Calculates the ISO week number of a given date.
		/// </summary>
		public static int GetWeekOfYear(DateOnly date) =>
			ISOWeek.GetWeekOfYear(date.ToDateTime(TimeOnly.MinValue));
		/// <summary>
		/// Calculates the ISO week-numbering year (also called ISO year informally) mapped to the input date.
		/// </summary>
		public static int GetYear(DateOnly date) =>
			ISOWeek.GetYear(date.ToDateTime(TimeOnly.MinValue));
		/// <summary>
		/// Maps the ISO week date represented by a specified ISO year, week number, and day of week to the equivalent <see cref="DateOnly"/>.
		/// </summary>
		public static DateOnly ToDateOnly(int year, int week, DayOfWeek dayOfWeek) =>
			DateOnly.FromDateTime(ISOWeek.ToDateTime(year, week, dayOfWeek));
	}
}
