// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
static partial class Polyfill
{
#if FeatureMemory
    /// <summary>Adds the elements of the specified span to the end of the <see cref="List{T}"/>.</summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.addrange?view=net-10.0
    public static void AddRange<T>(this List<T> target, ReadOnlySpan<T> source)
    {
        foreach (var item in source)
        {
            target.Add(item);
        }
    }
    /// <summary>Inserts the elements of a span into the <see cref="List{T}"/> at the specified index.</summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.insertrange?view=net-10.0
    public static void InsertRange<T>(this List<T> target, int index, ReadOnlySpan<T> source)
    {
        for (var i = 0; i < source.Length; i++)
        {
            var item = source[i];
            target.Insert(i + index, item);
        }
    }
    /// <summary>Copies the entire <see cref="List{T}"/> to a span.</summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.copyto?view=net-10.0
    public static void CopyTo<T>(this List<T> target, Span<T> destination)
    {
        for (var index = 0; index < target.Count; index++)
        {
            destination[index] = target[index];
        }
    }
#endif
}
