// <auto-generated />
#pragma warning disable
// <auto-generated />
#pragma warning disable
#if FeatureMemory
namespace Polyfills;
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
static partial class Polyfill
{
    extension(BitConverter)
    {
    }
}
#endif
