// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
static partial class Polyfill
{
	/// <summary>
	/// Sets the capacity of a HashSet object to the specified number of entries, rounded up to a nearby, implementation-specific value.
	/// </summary>
	public static void TrimExcess<T>(this HashSet<T> target, int capacity)
	{
	}
	/// <summary>
	/// Gets an instance of a type that may be used to perform operations on the current <see cref="HashSet{T}"/>
	/// using a <typeparamref name="TAlternate"/> instead of a <typeparamref name="T"/>.
	/// </summary>
	public static HashSetAlternateLookup<T, TAlternate> GetAlternateLookup<T, TAlternate>(
		this HashSet<T> target)
	{
		if (target.Comparer is not IAlternateEqualityComparer<TAlternate, T> comparer)
		{
			throw new InvalidOperationException(
				$"The set's comparer ({target.Comparer.GetType()}) does not implement IAlternateEqualityComparer<{typeof(TAlternate)}, {typeof(T)}>.");
		}
		return new(target, comparer);
	}
	/// <summary>
	/// Gets an instance of a type that may be used to perform operations on the current <see cref="HashSet{T}"/>
	/// using a <typeparamref name="TAlternate"/> instead of a <typeparamref name="T"/>.
	/// </summary>
	public static bool TryGetAlternateLookup<T, TAlternate>(
		this HashSet<T> target,
		out HashSetAlternateLookup<T, TAlternate> lookup)
	{
		if (target.Comparer is IAlternateEqualityComparer<TAlternate, T> comparer)
		{
			lookup = new(target, comparer);
			return true;
		}
		lookup = default;
		return false;
	}
}
