// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
static partial class Polyfill
{
    /// <summary>
    /// Sets the capacity of a Queue object to the specified number of entries.
    /// </summary>
    //Link: https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.queue-1.trimexcess?view=net-10.0#system-collections-generic-queue-1-trimexcess(system-int32)
    public static void TrimExcess<T>(this Queue<T> target, int capacity)
    {
    }
}
