// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.ComponentModel;
using System.IO;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
static partial class Polyfill
{
	extension(RandomAccess)
	{
		/// <summary>
		/// Flushes the operating system buffers for the given file to disk.
		/// </summary>
		/// <param name="handle">The file handle.</param>
		public static void FlushToDisk(SafeFileHandle handle)
		{
			if (handle is null)
			{
				throw new ArgumentNullException(nameof(handle));
			}
			if (handle.IsInvalid)
			{
				throw new ArgumentException("Invalid handle.", nameof(handle));
			}
			if (OperatingSystem.IsWindows())
			{
				if (!FlushFileBuffers(handle))
				{
					throw new Win32Exception(Marshal.GetLastWin32Error());
				}
			}
			else
			{
				var result = fsync(handle.DangerousGetHandle().ToInt32());
				if (result != 0)
				{
					throw new IOException($"fsync failed with error code {Marshal.GetLastWin32Error()}");
				}
			}
		}
		// Windows P/Invoke declarations
		[DllImport("kernel32.dll", SetLastError = true)]
		static extern bool FlushFileBuffers(SafeFileHandle hHandle);
		// Unix P/Invoke declarations
		[DllImport("libc", SetLastError = true)]
		static extern int fsync(int fd);
	}
}
