// <auto-generated />
#pragma warning disable
#nullable enable
namespace System.Diagnostics.CodeAnalysis;
using Targets = AttributeTargets;
/// <summary>
/// Indicates that the specified member requires assembly files to be on disk.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[AttributeUsage(
	validOn: Targets.Constructor |
			 Targets.Event |
			 Targets.Method |
			 Targets.Property,
	Inherited = false)]
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
sealed class RequiresAssemblyFilesAttribute :
	Attribute
{
	/// <summary>
	/// Initializes a new instance of the <see cref="RequiresAssemblyFilesAttribute"/> class.
	/// </summary>
	public RequiresAssemblyFilesAttribute()
	{
	}
	/// <summary>
	/// Initializes a new instance of the <see cref="RequiresAssemblyFilesAttribute"/> class
	/// with the specified message.
	/// </summary>
	public RequiresAssemblyFilesAttribute(string message) =>
		Message = message;
	/// <summary>
	/// Gets an optional message that contains information about the requirement for assembly files to be on disk.
	/// </summary>
	public string? Message { get; }
	/// <summary>
	/// Gets or sets an optional URL that contains more information about the member,
	/// why it requires assembly files to be on disk, and what options a consumer has to deal with it.
	/// </summary>
	public string? Url { get; set; }
}
