// <auto-generated />

#pragma warning disable


namespace Polyfills;

using System.Text;
using System;
using System.Security.Cryptography;

static partial class Polyfill
{
    extension(Guid)
    {


        /// <summary>Creates a new <see cref="Guid" /> according to RFC 9562, following the Version 7 format.</summary>
        
        public static Guid CreateVersion7() => CreateVersion7(DateTimeOffset.UtcNow);

        /// <summary>Creates a new <see cref="Guid" /> according to RFC 9562, following the Version 7 format.</summary>
        
        public static Guid CreateVersion7(DateTimeOffset timestamp)
        {
            var unixMilliseconds = timestamp.ToUnixTimeMilliseconds();

            var timeBytes = BitConverter.GetBytes(unixMilliseconds);

            if (BitConverter.IsLittleEndian)
            {
                Array.Reverse(timeBytes);
            }


            var uuidBytes = new byte[16];
            timeBytes[2..8].CopyTo(uuidBytes, 0);

            var randomBytes = uuidBytes.AsSpan().Slice(6);

            RandomNumberGenerator.Fill(randomBytes);

            uuidBytes[6] &= 0x0F;
            uuidBytes[6] += 0x70;

            return new(uuidBytes, true);

        }


#if FeatureMemory


        /// <summary>
        /// Converts span of characters representing the GUID to the equivalent Guid structure, provided that the string is in the specified format.
        /// </summary>
        
        public static bool TryParseExact(ReadOnlySpan<char> input, ReadOnlySpan<char> format, out Guid result) =>
            Guid.TryParseExact(input.ToString(), format.ToString(), out result);




        /// <summary>
        /// Tries to parse a span of UTF-8 bytes into a value.
        /// </summary>
        
        public static bool TryParse(ReadOnlySpan<byte> utf8Text, out Guid result) =>
            Guid.TryParse(Encoding.UTF8.GetString(utf8Text), out result);

        /// <summary>
        /// Parse a span of UTF-8 bytes into a value.
        /// </summary>
        
        public static Guid Parse(ReadOnlySpan<byte> utf8Text) =>
            Guid.Parse(Encoding.UTF8.GetString(utf8Text));


#endif
    }
}
