// <auto-generated />
#pragma warning disable

namespace Polyfills;

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;

static partial class Polyfill
{


}
