// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.Runtime.CompilerServices;
static partial class Polyfill
{
	extension(Enum)
	{
#if FeatureMemory
		/// <summary>
		/// Tries to format the value of the enumerated type instance into the provided span of characters.
		/// </summary>
		public static bool TryFormat<TEnum>(TEnum value, Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default)
			where TEnum : struct, Enum =>
			TryFormatUnconstrained(value, destination, out charsWritten, format);
		internal static bool TryFormatUnconstrained(object value, Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default)
		{
			string result;
			if (format.Length == 0)
			{
				result = value.ToString()!;
			}
			else
			{
				result = Enum.Format(value.GetType(), value, format.ToString());
			}
			if (result.Length > destination.Length)
			{
				charsWritten = 0;
				return false;
			}
			charsWritten = result.Length;
			result.CopyTo(destination);
			return true;
		}
#endif
	}
}
