// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
using System.ComponentModel;
static partial class Polyfill
{
	[EditorBrowsable(EditorBrowsableState.Never)]
	public static void Deconstruct(this TimeOnly target, out int hour, out int minute, out int second, out int millisecond)
	{
		hour = target.Hour;
		minute = target.Minute;
		second = target.Second;
		millisecond = target.Millisecond;
	}
	[EditorBrowsable(EditorBrowsableState.Never)]
	public static void Deconstruct(this TimeOnly target, out int hour, out int minute, out int second)
	{
		hour = target.Hour;
		minute = target.Minute;
		second = target.Second;
	}
	[EditorBrowsable(EditorBrowsableState.Never)]
	public static void Deconstruct(this TimeOnly target, out int hour, out int minute)
	{
		hour = target.Hour;
		minute = target.Minute;
	}
}
