// <auto-generated />
#pragma warning disable
namespace Polyfills;
using System;
static partial class Polyfill
{
#if FeatureMemory
	/// <summary>
	/// Fills the elements of a specified span with items chosen at random from the provided set of choices.
	/// </summary>
	public static void GetItems<T>(
		this Random target,
		ReadOnlySpan<T> choices,
		Span<T> destination)
	{
		if (choices.IsEmpty)
		{
			throw new ArgumentException("Choices cannot be empty.", nameof(choices));
		}
		for (var i = 0; i < destination.Length; i++)
		{
			destination[i] = choices[target.Next(choices.Length)];
		}
	}
	/// <summary>
	/// Creates an array populated with items chosen at random from the provided set of choices.
	/// </summary>
	public static T[] GetItems<T>(
		this Random target,
		ReadOnlySpan<T> choices,
		int length)
	{
		if (choices.IsEmpty)
		{
			throw new ArgumentException("Choices cannot be empty.", nameof(choices));
		}
		var result = new T[length];
		for (var i = 0; i < length; i++)
		{
			result[i] = choices[target.Next(choices.Length)];
		}
		return result;
	}
#endif
	/// <summary>
	/// Creates an array populated with items chosen at random from the provided set of choices.
	/// </summary>
	public static T[] GetItems<T>(
		this Random target,
		T[] choices,
		int length)
	{
		if (choices.Length == 0)
		{
			throw new ArgumentException("Choices cannot be null or empty.", nameof(choices));
		}
		var result = new T[length];
		for (var i = 0; i < length; i++)
		{
			result[i] = choices[target.Next(choices.Length)];
		}
		return result;
	}
	/// <summary>
	/// Creates a string filled with random hexadecimal characters.
	/// </summary>
	public static string GetHexString(this Random target, int stringLength, bool lowercase = false)
	{
		if (stringLength < 0)
		{
			throw new ArgumentOutOfRangeException(nameof(stringLength));
		}
		if (stringLength == 0)
		{
			return string.Empty;
		}
		var hexAlphabet = lowercase ? "0123456789abcdef" : "0123456789ABCDEF";
		var chars = new char[stringLength];
		for (var i = 0; i < stringLength; i++)
		{
			chars[i] = hexAlphabet[target.Next(16)];
		}
		return new string(chars);
	}
#if FeatureMemory
	/// <summary>
	/// Fills a buffer with random hexadecimal characters.
	/// </summary>
	public static void GetHexString(this Random target, Span<char> destination, bool lowercase = false)
	{
		var hexAlphabet = lowercase ? "0123456789abcdef" : "0123456789ABCDEF";
		for (var i = 0; i < destination.Length; i++)
		{
			destination[i] = hexAlphabet[target.Next(16)];
		}
	}
	/// <summary>
	/// Creates a string populated with characters chosen at random from the provided set of choices.
	/// </summary>
	public static string GetString(this Random target, ReadOnlySpan<char> choices, int length)
	{
		if (choices.IsEmpty)
		{
			throw new ArgumentException("Choices cannot be empty.", nameof(choices));
		}
		if (length < 0)
		{
			throw new ArgumentOutOfRangeException(nameof(length));
		}
		if (length == 0)
		{
			return string.Empty;
		}
		var chars = new char[length];
		for (var i = 0; i < length; i++)
		{
			chars[i] = choices[target.Next(choices.Length)];
		}
		return new string(chars);
	}
#endif
	/// <summary>
	/// Performs an in-place shuffle of an array.
	/// </summary>
	public static void Shuffle<T>(
		this Random target,
		T[] values)
	{
		var n = values.Length;
		for (var i = 0; i < n - 1; i++)
		{
			var j = target.Next(i, n);
			if (j != i)
			{
				var temp = values[i];
				values[i] = values[j];
				values[j] = temp;
			}
		}
	}
#if FeatureMemory
	/// <summary>
	/// Performs an in-place shuffle of a span.
	/// </summary>
	public static void Shuffle<T>(
		this Random target,
		Span<T> values)
	{
		var n = values.Length;
		for (int i = 0; i < n - 1; i++)
		{
			var j = target.Next(i, n);
			if (j != i)
			{
				var temp = values[i];
				values[i] = values[j];
				values[j] = temp;
			}
		}
	}
#endif
}
