// <auto-generated />
#pragma warning disable

#if FeatureMemory
#if PolyUseEmbeddedAttribute
#endif
#if PolyPublic
#endif
using System.Buffers;
using System.Runtime.CompilerServices;
[assembly: TypeForwardedTo(typeof(SpanAction<,>))]
#endif
