// <auto-generated />
#pragma warning disable
#if FeatureMemory
#pragma warning disable
namespace System.Text.Unicode;
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
/// <summary>Provides static methods for validating UTF-16 text.</summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if PolyUseEmbeddedAttribute
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
#endif
#if PolyPublic
public
#endif
static class Utf16
{
	/// <summary>
	/// Returns the index in <paramref name="value"/> where the first ill-formed UTF-16 subsequence begins, or -1 if <paramref name="value"/> is well-formed.
	/// </summary>
	public static int IndexOfInvalidSubsequence(ReadOnlySpan<char> value)
	{
		for (var i = 0; i < value.Length; i++)
		{
			var c = value[i];
			if (char.IsHighSurrogate(c))
			{
				if (i + 1 >= value.Length ||
					!char.IsLowSurrogate(value[i + 1]))
				{
					return i;
				}
				i++;
			}
			else if (char.IsLowSurrogate(c))
			{
				return i;
			}
		}
		return -1;
	}
	/// <summary>
	/// Returns a value indicating whether <paramref name="value"/> is well-formed UTF-16.
	/// </summary>
	public static bool IsValid(ReadOnlySpan<char> value) =>
		IndexOfInvalidSubsequence(value) < 0;
}
#endif
