// <auto-generated />
#pragma warning disable

#if FeatureMemory && !NET6_0_OR_GREATER
#nullable enable
#if PolyPublic
#endif
    #region AppendFormatted
    #region AppendFormatted T
    #endregion
    #region AppendFormatted ReadOnlySpan<char>
    #endregion
    #region AppendFormatted string
    #endregion
    #region AppendFormatted object
    #endregion
    #endregion
#endif