// <auto-generated />
#pragma warning disable

namespace Polyfills;

using System.Collections;
using System.Collections.Generic;
using Link = System.ComponentModel.DescriptionAttribute;

static partial class Polyfill
{
}